numpy is library  use for easyness in calculation ,it is mainly use for calcualtion with library function.
it is faster than list ,there are several reason but main reason are storage it store the value in memory one after another where in list
it store in different memory and give pointer to them.
and also numpy library implemented in c.

In [1]:
import numpy as np

In [2]:
b = [1,2,3,4]
a = np.array(b)
a

array([1, 2, 3, 4])

In [5]:
a = np.array([1,2,3,4,5,6,7,8,9,10])
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [6]:
import numpy as np
a = np.random.randint(1,101,(3,4))
a

array([[71,  8,  8, 22],
       [62, 35, 10, 63],
       [94, 18, 53, 47]], dtype=int32)

In [11]:
a.shape

(3, 4)

In [12]:
a.ndim

2

In [13]:
a.dtype

dtype('int32')

In [18]:
a = np.zeros(10).astype('int32')
a

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int32)

In [21]:
a = np.ones(10).astype('int32')
a

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int32)

In [23]:
a = np.eye(3).astype('int32')
a

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]], dtype=int32)

In [25]:
a = np.arange(1,100)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [30]:
a = np.linspace(1,10,2).astype('int32')
a

array([ 1, 10], dtype=int32)

In [35]:
a = np.random.randint(1,10,(3,3))
b = a.reshape(-1)
c = b.reshape(3,3)
c

array([[1, 6, 8],
       [8, 2, 2],
       [4, 6, 7]], dtype=int32)

In [36]:
b = c.flatten()
b

array([1, 6, 8, 8, 2, 2, 4, 6, 7], dtype=int32)

In [38]:
b = b.astype('float32')
b

array([1., 6., 8., 8., 2., 2., 4., 6., 7.], dtype=float32)

In [42]:
a = np.random.randint(1,100,10)
a

array([46,  2, 76, 59, 13, 80, 28, 95, 35, 18], dtype=int32)

In [43]:
a = np.random.randint(1,101,10)
a

array([29, 76, 24, 15, 47, 75,  7, 39,  1, 41], dtype=int32)

In [48]:
a = np.empty((2,3)).astype('int32')
a

array([[0, 0, 0],
       [0, 0, 0]], dtype=int32)

In [59]:
a = np.random.randint(1,10,5)
b = a.copy()
c = a.view()
b[4] = 10
a,b,c

(array([2, 2, 9, 2, 5], dtype=int32),
 array([ 2,  2,  9,  2, 10], dtype=int32),
 array([2, 2, 9, 2, 5], dtype=int32))

In [7]:
import numpy as np
a = np.array([3,56,2,7,8,45])
print(a[0])
print(a[-1])
print(a[:5])
print(a[::2])
print(a[::-1])

3
45
[ 3 56  2  7  8]
[3 2 8]
[45  8  7  2 56  3]


In [11]:
a = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])
print(a[1])
print(a[:,2])
print(a[:2,:2])

[4 5 6]
[3 6 9]
[[1 2]
 [4 5]]


In [21]:
a = np.array([[-3,4,5],
              [2,4,-5],
              [1,-4,-7]])
a[a<0] = 0
a

array([[0, 4, 5],
       [2, 4, 0],
       [1, 0, 0]])

In [25]:
a = np.array([[20,45,123],
              [34,120,189],
              [78,23,100]])
a[a > 100] = 100
a

array([[ 20,  45, 100],
       [ 34, 100, 100],
       [ 78,  23, 100]])

In [32]:
threshold = 10
print(a[a>threshold])

[ 20  45 100  34 100 100  78  23 100]


In [34]:
print(a[a%2!=0])

[45 23]


In [35]:
print(a[a%2==0])

[ 20 100  34 100 100  78 100]


In [36]:
print(a[[0,2]])

[[ 20  45 100]
 [ 78  23 100]]


In [39]:
print(a[:,[0,1]])

[[ 20  45]
 [ 34 100]
 [ 78  23]]


In [45]:
a = np.array([1,2,3])
b = np.array([4,5,6])
np.add(a,b,out=a)
a

array([5, 7, 9])

In [46]:
a = np.array([1,2,3])
b = np.array([4,5,6])
np.subtract(a,b,out=a)
a

array([-3, -3, -3])

In [48]:
a = np.array([1,2,3])
b = np.array([4,5,6])
np.multiply(a,b,out=a)
a

array([ 4, 10, 18])

In [51]:
a = np.array([1,2,3]).astype('float')
b = np.array([4,5,6])
np.divide(a,b,out=a)
a

array([0.25, 0.4 , 0.5 ])

In [56]:
a = np.array([3,4,5])
b = np.square(a)
b

array([ 9, 16, 25])

In [61]:
c = np.power(a,3)
c

array([ 27,  64, 125])

In [64]:
c = np.sqrt(a)
c

array([1.73205081, 2.        , 2.23606798])

In [68]:
c = np.log(a)
c

array([1.09861229, 1.38629436, 1.60943791])

In [69]:
c = np.exp(a)
c

array([ 20.08553692,  54.59815003, 148.4131591 ])

In [76]:
a = np.array([1.2,-4.5,8.2])
c = np.abs(a)
c

array([1.2, 4.5, 8.2])

In [83]:
a = np.array([23,4,5,6,54,2,9,5,6,7,83,4])
print(np.min(a))
print(np.max(a))
print(np.sum(a))
print(np.mean(a))
print(np.median(a))

2
83
208
17.333333333333332
6.0


In [7]:
import numpy as np

a = np.array([
    12, 15, 18, 20, 22, 25, 27, 30, 32, 35,
    38, 40, 42, 45, 48, 50, 52, 55, 58, 100
])
print(np.var(a))
print(np.std(a))
print(np.percentile(a,30))
print("detecting outlier using inter quartile range")
b = np.percentile(a,[25,50,75])
print(b)
iqr = b[2]-b[0]
print(iqr)
upperbound = b[2] + 1.5*iqr
lowerbound = b[0] - 1.5*iqr
print(a[(a>upperbound) | (a<lowerbound)])
x = []
for i in range(len(a)):
    z = (a[i] - a.mean())/a.std()
    if z > 3:
        x.append(a[i])
print(x)

381.26000000000005
19.52588026184735
26.4
detecting outlier using inter quartile range
[24.25 36.5  48.5 ]
24.25
[100]
[np.int64(100)]


In [13]:
import numpy as np
x = np.array([10, 20, 30, 40, 50, 60, 70, 80])
y = np.array([15, 25, 35, 45, 55, 65, 75, 90])
print(y)
a = np.corrcoef(x,y)[0,1]
print(a)
b = np.cov(x,y)
print(b)

[15 25 35 45 55 65 75 90]
0.9984038297885897
[[600.    625.   ]
 [625.    653.125]]


In [24]:
a = np.array([
    12, 15, 18, 20, 22, 25, 27, 30, 32, 35,
    38, 40, 42, 45, 48, 50, 52, 55, 58, 100
])
mean = np.mean(a)
std = np.std(a)
skewness = np.mean((a-mean)**3)/(std**3)
skewness

np.float64(1.3473061634666987)

In [19]:
from scipy.stats import skew
skewness = skew(a)
skewness

np.float64(1.3473061634666985)

In [36]:
new_min = 10
new_max = 90
x = ((a-np.min(a))/(np.max(a)-np.min(a)))*(new_max-new_min)+new_min
x

array([10.        , 12.72727273, 15.45454545, 17.27272727, 19.09090909,
       21.81818182, 23.63636364, 26.36363636, 28.18181818, 30.90909091,
       33.63636364, 35.45454545, 37.27272727, 40.        , 42.72727273,
       44.54545455, 46.36363636, 49.09090909, 51.81818182, 90.        ])

In [41]:
a = np.array([
    12, 15, 18, 20, 22, 25, 27, 30, 32, 35,
    38, 40, 42, 45, 48, 50, 52, 55, 58, 100
])
z = (a-np.mean(a))/np.std(a)
z

array([-1.3418089 , -1.18816666, -1.03452442, -0.93209626, -0.8296681 ,
       -0.67602586, -0.5735977 , -0.41995546, -0.3175273 , -0.16388506,
       -0.01024282,  0.09218534,  0.19461351,  0.34825575,  0.50189799,
        0.60432615,  0.70675431,  0.86039655,  1.01403879,  3.16503016])

In [19]:
import numpy as np
a = np.array([10, 20, 30, 40, 50, 60, 70, 80])
x = np.convolve(a,np.ones(3)/3,mode='valid')
x

array([20., 30., 40., 50., 60., 70.])

In [21]:
print(np.cumsum(a))

[ 10  30  60 100 150 210 280 360]


In [23]:
print(np.cumprod(a))

[           10           200          6000        240000      12000000
     720000000   50400000000 4032000000000]


In [55]:
a = np.array([
    [10, np.nan, 30],
    [20, 25, np.nan],
    [np.nan, 35, 40],
    [50, 55, 60]
])
print(np.where(np.isnan(a)))
print(np.isnan(a).sum())
a[np.isnan(a)] = 0
a

(array([0, 1, 2]), array([1, 2, 0]))
3


array([[10.,  0., 30.],
       [20., 25.,  0.],
       [ 0., 35., 40.],
       [50., 55., 60.]])

In [78]:
a = np.array([
    [10, np.nan, 30],
    [20, 25, np.nan],
    [np.nan, 35, 40],
    [50, 55, 60]
])
a[np.isnan(a)] = np.nanmean(a,axis=0)
a

array([[10.        , 26.66666667, 30.        ],
       [20.        , 25.        , 38.33333333],
       [43.33333333, 35.        , 40.        ],
       [50.        , 55.        , 60.        ]])

In [79]:
a = np.array([
    [10, np.nan, 30],
    [20, 25, np.nan],
    [np.nan, 35, 40],
    [50, 55, 60]
])
a[np.isnan(a)] = np.nanmedian(a,axis=0)
a

array([[10., 20., 30.],
       [20., 25., 35.],
       [40., 35., 40.],
       [50., 55., 60.]])

In [95]:
import numpy as np
import pandas as pd

data = np.array([
    ['Male'],
    ['Female'],
    [np.nan],
    ['Male'],
    ['Male'],
    [np.nan],
    ['Female'],
    ['Male']
], dtype=object)
c1=0
c2=0
for i in data:
    if i=='Male':
        c1+=1
    else:
        c2+=1
if c1 > c2:
    data[pd.isna(data)] = 'Male'
else:
    data[pd.isna(data)] = 'Female'
data

array([['Male'],
       ['Female'],
       ['Female'],
       ['Male'],
       ['Male'],
       ['Female'],
       ['Female'],
       ['Male']], dtype=object)

In [107]:
data = np.array([
    [1, 2, np.nan],
    [4, 5, 6],
    [7, np.nan, 9],
    [10, 11, 12]
])
data = data[~np.isnan(data).any(axis=1)]
data

array([[ 4.,  5.,  6.],
       [10., 11., 12.]])

In [114]:
data = np.array([
    [1, 2, np.nan],
    [4, 5, 6],
    [7, np.nan, 9],
    [10, 11, 12]
])
data  = data[:,~np.isnan(data).any(axis=0)]
data

array([[ 1.],
       [ 4.],
       [ 7.],
       [10.]])

In [18]:
import numpy as np
a = np.array([
    [10, np.nan, 30],
    [20, 25, np.nan],
    [np.nan, 35, 40],
    [50, 55, 60]
])
for i in range(0,a.shape[0]):
    for j in range(a.shape[1]):
        if np.isnan(a[i,j]):
            a[i,j] = a[i,j-1]
print("forward fill:-\n",a)

forward fill:-
 [[10. 10. 30.]
 [20. 25. 25.]
 [40. 35. 40.]
 [50. 55. 60.]]


In [19]:
import numpy as np
a = np.array([
    [10, np.nan, 30],
    [20, 25, np.nan],
    [np.nan, 35, 40],
    [50, 55, 60]
])
for i in range(0,a.shape[0]):
    for j in range(a.shape[1]-1,-1,-1):
        if np.isnan(a[i,j]):
            if j==2:
                a[i,j] = a[i,0]
            else:
                a[i,j] = a[i,j+1]
print("backward fill:-\n",a)

backward fill:-
 [[10. 30. 30.]
 [20. 25. 20.]
 [35. 35. 40.]
 [50. 55. 60.]]


In [30]:
a = np.array([
    10, 20, 20, 30, 40, 40, 50, 60, 60
])
c = np.unique(a)
print(a)
print(c.shape[0])
b = np.unique(a,return_counts=True)
print(b)

[10 20 20 30 40 40 50 60 60]
6
(array([10, 20, 30, 40, 50, 60]), array([1, 2, 1, 2, 1, 2]))


In [37]:
a = np.array([
    "Red", "Blue", "Green", "Red",
    "Blue", "Green", "Red"
])
np.unique(a,return_counts=True)
mapping = {
    'Red':1,'Blue':2,'Green':3
}
a = np.array([mapping[x] for x in a])
a

array([1, 2, 3, 1, 2, 3, 1])

In [43]:
a = np.array([
    "Red", "Blue", "Green", "Red",
    "Blue", "Green", "Red"
])
b = np.array([1 if x=='Red' else 0 for x in a])
print('Red:-',b)
c = np.array([1 if x=='Blue' else 0 for x in a])
print('Blue:-',c)
d = np.array([1 if x=='Green' else 0 for x in a])
print('Green:-',d)

Red:- [1 0 0 1 0 0 1]
Blue:- [0 1 0 0 1 0 0]
Green:- [0 0 1 0 0 1 0]


In [47]:
a = np.array([
    10, 15, 20, 25, 30, 1000
])
a = np.clip(a,0,100)
a

array([ 10,  15,  20,  25,  30, 100])

In [52]:
a = np.array([23.45678,76.54746,96.76448,2.6473838,9.47475])
a = np.round(a,2)
a

array([23.46, 76.55, 96.76,  2.65,  9.47])

In [56]:
a = np.array([
    "10", "20", "30", "40", "50"
])
a = a.astype('int')
a

array([10, 20, 30, 40, 50])

In [71]:
a = np.array([
    10, 20, np.nan, 30, -5,
    np.inf, 40, -10, 50,
    -np.inf, 60
])
a = a[~(np.isnan(a) | np.isinf(a))]
a

array([ 10.,  20.,  30.,  -5.,  40., -10.,  50.,  60.])

In [7]:
import numpy as np 
a = np.array([
    5, 12, 18, 25, 35, 45, 55, 65, 75
])
bins = [5,25,45,65,85]
print(np.digitize(a,bins))

[1 1 1 2 2 3 3 4 4]


In [11]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])
c = np.concatenate((a,b))
c

array([1, 2, 3, 4, 5, 6, 7, 8])

In [22]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])
c = np.stack((a,b),axis=0)
c

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [23]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])
c = np.stack((a,b),axis=1)
c

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [29]:
a = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])
b = np.split(a,3)
b

[array([[1, 2, 3]]), array([[4, 5, 6]]), array([[7, 8, 9]])]

In [31]:
c = np.vsplit(a,3)
c

[array([[1, 2, 3]]), array([[4, 5, 6]]), array([[7, 8, 9]])]

In [32]:
d = np.hsplit(a,3)
d

[array([[1],
        [4],
        [7]]),
 array([[2],
        [5],
        [8]]),
 array([[3],
        [6],
        [9]])]

In [34]:
a = np.array([1,2,3,4,5])
b = a[a%2==0]
c = a[a%2!=0]
d = a[a > 3]
e = a[a < 3]
b,c,d,e

(array([2, 4]), array([1, 3, 5]), array([4, 5]), array([1, 2]))

In [36]:
a = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])
a = a.T
a

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [42]:
a = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])
a[[0,1]] = a[[1,0]]
a

array([[4, 5, 6],
       [1, 2, 3],
       [7, 8, 9]])

In [43]:
a = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])
a[:,[0,1]] = a[:,[1,0]]
a

array([[2, 1, 3],
       [5, 4, 6],
       [8, 7, 9]])

In [85]:
a = np.random.randint(1,101,(3,3))
a = a[a[:,2].argsort()]
a

array([[35, 23, 18],
       [51, 41, 22],
       [51, 10, 53]], dtype=int32)

In [2]:
import numpy as np
a = np.array([[23,45,7],
              [87,34,29],
              [23,65,23]])
a = a[a[:,2].argsort()]
a

array([[23, 45,  7],
       [23, 65, 23],
       [87, 34, 29]])

In [3]:
b = np.array([[23,45,7],
              [87,34,29],
              [23,65,23]])
b
b = b[:,b[0].argsort()]
b

array([[ 7, 23, 45],
       [29, 87, 34],
       [23, 23, 65]])

In [6]:
c = np.array([[23,45,7],
              [87,34,29],
              [23,65,23]])
print(c.argsort())

[[2 0 1]
 [2 1 0]
 [0 2 1]]


In [28]:
a = np.array([
    [10, 20],
    [15, 25],
    [20, np.nan],
    [25, 35],
    [30, 40],
    [35, 45],
    [40, 50],
    [45, 55],
    [50, 60],
    [1000, 1200]
])
a[np.isnan(a)] = 30
b = np.percentile(a,[25,50,75])
print(b)
iqr = b[2] - b[1]
print(iqr)
ub = b[2] + 1.5*iqr
lb = b[0] - 1.5*iqr
print(ub,lb)
a = a[~((a > ub) | (a < lb))]

[25.  37.5 50. ]
12.5
68.75 6.25


In [27]:
new_min = 0
new_max = 100
c = (a-np.min(a))/(np.max(a)-np.min(a))*(new_max-new_min) + new_min
c

array([  0.,  20.,  10.,  30.,  20.,  40.,  30.,  50.,  40.,  60.,  50.,
        70.,  60.,  80.,  70.,  90.,  80., 100.])

In [30]:
z = (a-np.mean(a))/np.std(a)
z

array([-1.8057878 , -1.08347268, -1.44463024, -0.72231512, -1.08347268,
       -0.36115756, -0.72231512,  0.        , -0.36115756,  0.36115756,
        0.        ,  0.72231512,  0.36115756,  1.08347268,  0.72231512,
        1.44463024,  1.08347268,  1.8057878 ])

In [11]:
import numpy as np
marks = np.array([
    [85, 78, 92],
    [45, 55, 60],
    [95, 88, 91],
    [35, 40, 42],
    [72, 68, 75],
    [90, 92, 94],
    [50, 48, 52],
    [80, 85, 88],
    [65, 70, 72],
    [99, 100, 98]
])
total = np.array(np.sum(marks,axis=1))
print("top 5 students:-\n",marks[total.argsort()[::-1]][:5])
print("subject wise average:-",np.mean(marks,axis=0))
print("student below passing marks:-\n",marks[(marks<50).any(1)])

top 5 students:-
 [[ 99 100  98]
 [ 90  92  94]
 [ 95  88  91]
 [ 85  78  92]
 [ 80  85  88]]
subject wise average:- [71.6 72.4 76.4]
student below passing marks:-
 [[45 55 60]
 [35 40 42]
 [50 48 52]]


In [60]:
df = np.array([
    ["Red", 10, 20],
    ["Blue", 15, np.nan],
    ["Green", 20, 30],
    ["Red", 10, 20],
    ["Blue", 1000, 1200],
    ["Green", 25, 35],
    ["Red", 30, 40],
    ["Blue", 35, 45]
], dtype=object)
df = np.array(list(dict.fromkeys(map(tuple, df))), dtype=object)
df

array([['Red', 10, 20],
       ['Blue', 15, nan],
       ['Green', 20, 30],
       ['Blue', 1000, 1200],
       ['Green', 25, 35],
       ['Red', 30, 40],
       ['Blue', 35, 45]], dtype=object)

In [67]:
df[np.isnan(df[:,2].astype('float')),2] = 25
df

array([['Red', 10, 20],
       ['Blue', 15, 25],
       ['Green', 20, 30],
       ['Blue', 1000, 1200],
       ['Green', 25, 35],
       ['Red', 30, 40],
       ['Blue', 35, 45]], dtype=object)

In [68]:
mapping = {
    'Red':2,
    'Blue':1,
    'Green':3
}
df[:,0] = [mapping[x] for x in df[:,0]]
df

array([[2, 10, 20],
       [1, 15, 25],
       [3, 20, 30],
       [1, 1000, 1200],
       [3, 25, 35],
       [2, 30, 40],
       [1, 35, 45]], dtype=object)

In [71]:
z = (df - np.mean(df))/np.std(df)
df = df[~(z>3).any(1)]
df

array([[2, 10, 20],
       [1, 15, 25],
       [3, 20, 30],
       [3, 25, 35],
       [2, 30, 40],
       [1, 35, 45]], dtype=object)

In [79]:
new_min = 0
new_max = 100
df= (df-np.min(df))/(np.max(df)-np.min(df))*(new_max-new_min)+new_min
df

array([[2.272727272727273, 20.454545454545457, 43.18181818181818],
       [0.0, 31.818181818181817, 54.54545454545454],
       [4.545454545454546, 43.18181818181818, 65.9090909090909],
       [4.545454545454546, 54.54545454545454, 77.27272727272727],
       [2.272727272727273, 65.9090909090909, 88.63636363636364],
       [0.0, 77.27272727272727, 100.0]], dtype=object)